### ISSUE TITLE
mvn cmd in documentation does not run correctly

### ISSUE THREAD

**Issue by NewRunner2023** [quarkiverse/quarkus-github-action#100]
https://quarkiverse.github.io/quarkiverse-docs/quarkus-github-action/dev/create-github-action.html
mvn io.quarkus.platform:quarkus-maven-plugin:2.15.1.Final:create \
    -DprojectGroupId=org.acme \ 
    -DprojectArtifactId=my-github-action \ 
    -DprojectVersion=999-SNAPSHOT \ 
    -DprojectName="My Action" \ 
    -DprojectDescription="Description of my action" \ 
    -Ddata=github-action-codestart.github-repository=my/action-github-repository \ 
    -Dextensions="io.quarkiverse.githubaction:quarkus-github-action:1.0.1" 

For me the -Ddata is patricia-hartnett/gitHibActions_testQuarkus, but apart from that I have not edited anything else in the mvn command.

When I run this the values are not being passed in.
mvn prompts me to fill in the values, but then it falls over with the error message:
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.15.1.Final:create (default-cli) on project artifactid: Failed to generate Quarkus project: Error while rendering template: /codestarts/quarkus/github-action-codestart/base/action.docker.tpl.qute.yml: Missing required data: {project.name} -> [Help 1]

Please see the screengrab attached.
I am using MacOS 12.6.1
I have 3.6.3 Maven

![Screenshot 2023-01-17 at 14 54 53](https://user-images.githubusercontent.com/122446685/212934316-d17ee8a3-f541-47f8-a42a-859efbbc58cc.png)

**Comment by gsmet** [comment]
Hi!

This rings a bell as we have this warning in the Quarkus main documentation:

```
For Windows users

    If using cmd , (don’t use backward slash \ and put everything on the same line)
    If using Powershell , wrap -D parameters in double quotes e.g. "-DprojectArtifactId=getting-started"
```

If it fixes the issue for you, I'll add it to the documentation.

**Comment by NewRunner2023** [comment]
Thank you that worked perfectly ! I am on a Mac.

Really appreciate your help.

![Screenshot 2023-01-17 at 15 33 04](https://user-images.githubusercontent.com/122446685/212941439-7e57e0b0-290c-4bd7-bef0-f1d8825def7a.png)

**Comment by gsmet** [comment]
Thanks for confirming. I created https://github.com/quarkiverse/quarkus-github-action/pull/104/files to improve things a bit.
