### ISSUE TITLE
git remote add origin cmd not needed

### ISSUE THREAD

**Issue by NewRunner2023** [quarkiverse/quarkus-github-action#101]
I'm on the Push to Git part of https://quarkiverse.github.io/quarkiverse-docs/quarkus-github-action/dev/create-github-action.html

I don't think that the line 
git remote add origin git@github.com:my/action-github-repository.git 

is needed.

When I do it I get:
![Screenshot 2023-01-17 at 15 52 08](https://user-images.githubusercontent.com/122446685/212946252-6ca158dd-b639-4ac1-96db-589089899e12.png)

**Comment by gsmet** [comment]
It is actually needed, except if you cloned the repository yourself. But in the guide, we don't do that, we just push to an empty repository.

Please reopen or comment if you don't agree.

**Comment by gsmet** [comment]
I created https://github.com/quarkiverse/quarkus-github-action/pull/104/files to improve things a bit.
