### ISSUE TITLE
Class name doesn't match text in the documentation 

### ISSUE THREAD

**Issue by NewRunner2023** [quarkiverse/quarkus-github-action#102]
https://quarkiverse.github.io/quarkiverse-docs/quarkus-github-action/dev/create-github-action.html

The heading says MyAction.java

The code provided is for a class called MyGitHubAction

**Comment by gsmet** [comment]
You're right, thanks. I created https://github.com/quarkiverse/quarkus-github-action/pull/103 to fix it.

Thanks for taking the time to report it!
