### ISSUE TITLE
Unable to resolve action <repo name>, repository not found

### ISSUE THREAD

**Issue by NewRunner2023** [quarkiverse/quarkus-github-action#105]
Hello, when I follow the Run your action instructions here 
https://quarkiverse.github.io/quarkiverse-docs/quarkus-github-action/dev/create-github-action.html#_myaction_java

I am getting an error message:
Unable to resolve action `patricia-hartnett/gitHibActions_testQuarkus2`, repository not found

In my setup I have patricia-hartnett/gitHibActions_testQuarkus2:
![Screenshot 2023-01-18 at 12 15 16](https://user-images.githubusercontent.com/122446685/213169480-8f2d6869-f50c-4576-86d6-13dfe8260725.png)
This is where the Java code and the docker image is.

And patricia-hartnett/gitHubActions_test1:
![Screenshot 2023-01-18 at 12 12 09](https://user-images.githubusercontent.com/122446685/213169514-92af3778-783b-4bba-bd44-d69879fe04c4.png)

This is how I define the workflow in this repo which is supposed to call the Quarkiverse code in patricia-hartnett/gitHibActions_testQuarkus2:
![Screenshot 2023-01-18 at 12 21 45](https://user-images.githubusercontent.com/122446685/213170380-3fb88e31-5d2b-4371-abc1-f7515f547a90.png)

I was wondering am I having the repository not found problem because patricia-hartnett/gitHibActions_testQuarkus2 is a private repo ?  

Thank you in advance.

**Comment by gsmet** [comment]
@NewRunner2023 could you have a look at https://docs.github.com/en/actions/creating-actions/sharing-actions-and-workflows-from-your-private-repository ? If it works for you, I will add a pointer in the documentation.

**Comment by gsmet** [comment]
I created https://github.com/quarkiverse/quarkus-github-action/pull/106, I will wait for your feedback before merging.

**Comment by NewRunner2023** [comment]
Thank you @gsmet, I'll try that now and get back to you shortly.

**Comment by NewRunner2023** [comment]
Thank you @gsmet .

That seems to have worked. As soon as I set the Access to:
 Accessible from repositories owned by the user 'patricia-hartnett' 
it worked .

I am now getting a different error though:
![Screenshot 2023-01-18 at 14 21 17](https://user-images.githubusercontent.com/122446685/213196346-a590a4cd-451d-4bca-9fcf-32bec9c74969.png)


I'll go find out what actions checkout is and then get back to you.

**Comment by NewRunner2023** [comment]
I added in 
- name: Run actions checkout
        uses: actions/checkout@v3
into the workflow which is trying to call the Quarkiverse code in the other repo.
(See new lines 20 and 21)

![Screenshot 2023-01-18 at 14 49 56](https://user-images.githubusercontent.com/122446685/213203134-19eb0b8b-552f-4b2d-abaf-3597af412146.png)

Any ideas ?

**Comment by gsmet** [comment]
So not sure if it's important but it should be `uses: org/repository@main` (no `/` before `@main`). If that doesn't fix the issue, did you actually push the action to the action repository? You should have an `action.yml` at the root of the repository.

**Comment by NewRunner2023** [comment]
I fixed the /@main problem but I am still seeing the error message about Can't find action.yml

This is what I have in the repo containing the Quarkiverse Java class:

![Screenshot 2023-01-18 at 15 24 17](https://user-images.githubusercontent.com/122446685/213213277-971fba35-844c-4fba-9df8-3bc36d0d36db.png)


![Screenshot 2023-01-18 at 15 25 02](https://user-images.githubusercontent.com/122446685/213213306-dbd20f94-e4ce-4231-b016-b1f656e82382.png)


Is this what would be normally expected ?

**Comment by NewRunner2023** [comment]
Actually I think I see what the problem is .
I had something wrong with my original pom.xml.
The artifactId was not the same as my repository name.

I'll start again and fix that :-)
Thank you for being patient.

**Comment by gsmet** [comment]
I added some more explicit instructions here: https://github.com/quarkiverse/quarkus-github-action/pull/107
