### ISSUE TITLE
Unable to resolve action <repo name>, repository not found, part 2

### ISSUE THREAD

**Issue by NewRunner2023** [quarkiverse/quarkus-github-action#109]
I have everything set up correctly.

2 repos
patricia-hartnett/gitHubActions_test1 - it will call the Java code in the other repo
patricia-hartnett/gitHubActions_testQuarkus5 - it has the Quarkiverse Java code in it.

patricia-hartnett/gitHubActions_testQuarkus5  looks like:
![Screenshot 2023-01-19 at 11 40 36](https://user-images.githubusercontent.com/122446685/213433520-4a0f0bf0-e3b6-4b35-b79a-50a72e1b8b86.png)
![Screenshot 2023-01-19 at 11 36 30](https://user-images.githubusercontent.com/122446685/213433551-d7e10ab3-e1bf-47aa-b809-360425322c25.png)
![Screenshot 2023-01-19 at 11 35 53](https://user-images.githubusercontent.com/122446685/213433567-08b8f555-05e1-4ba0-8fa8-62e507d475f4.png)

In patricia-hartnett/gitHubActions_test1 I have an action whose workflow looks like:
![Screenshot 2023-01-19 at 11 43 24](https://user-images.githubusercontent.com/122446685/213434068-e40776eb-cdf0-48a1-a6c2-5977407e7d11.png)

When this is run I get the repo not found error:
![Screenshot 2023-01-19 at 12 00 20](https://user-images.githubusercontent.com/122446685/213437822-440875c0-3e51-4792-b46c-0ed0123a61df.png)

I have tried pointing to both my own patricia-hartnett/gitHubActions_testQuarkus5 and gsmet/my-github-action. I get the same error message.
One of the things I noticed was that in the actions.yml file in patricia-hartnett/gitHubActions_testQuarkus5 , there is a line mentioning 'github=https://maven.pkg.github.com/patricia-hartnett/gitHubActions_testQuarkus5/....
![Screenshot 2023-01-19 at 11 46 37](https://user-images.githubusercontent.com/122446685/213434767-b4b74feb-0b90-4b51-a1f8-c85a875f4de4.png)
I tried going to this URL but I got a 404.
In fairness I also tried going to https://maven.pkg.github.com/gsmet/my-github-action/ (as mentioned here:https://github.com/gsmet/my-github-action/blob/9101a475431954e586525a565a3dd8ef75e48b7b/action.yml#L14) and still got a 404.

I have tried with and without a step doing actions/checkout@v3 in the action in patricia-hartnett/gitHubActions_test1  (where it attempts to call the Java code in the other repo), but I am still getting the same error message.
Both of my repos are set up as private but accessible from repositories owned by the user 'patricia-hartnett'.

Am I doing something wrong ?

**Comment by gsmet** [comment]
(See bottom of the message for what I think is your problem)

It's normal you have a 404, GitHub doesn't generate an index page for the Maven repositories. What you should have is something like this:

![2023-01-19 12 59 50 github com 246e95067ad4](https://user-images.githubusercontent.com/1279749/213437950-ddfa5552-15cc-425d-b2ef-2a348139d1d0.png)

What looks suspicious to me is your `uses: github.com:patricia-hartnett...`. Where does the `github.com:` prefix come from?

See https://github.com/gsmet/github-action-playground-target/blob/main/.github/workflows/run-action.yml#L24 for how I use my action.

**Comment by NewRunner2023** [comment]
Thank you !

That worked . 

Sorry for putting in the extra bit in front of the run action uses.

I am now getting:

![Screenshot 2023-01-19 at 12 12 24](https://user-images.githubusercontent.com/122446685/213440515-e316e514-ccf2-4dd0-9324-7b5ab576ac44.png)

**Comment by gsmet** [comment]
Yeah so that's probably because you changed the groupId and artifact after the action creation. You need to update your `action.yml` to target the proper jar (in the JBang call).

**Comment by NewRunner2023** [comment]
Great thanks will do that now and get back to you.

**Comment by NewRunner2023** [comment]
Sorry I don't see a problem with what I have .
 I am only using the default settings.

On the root page of my repo (where the Quarkiverse Java code lives) it has:
![Screenshot 2023-01-19 at 12 22 09](https://user-images.githubusercontent.com/122446685/213442256-59612230-4b5b-4209-ab37-b8b43fb998e5.png)
And in the actions.yml it has:
![Screenshot 2023-01-19 at 12 22 20](https://user-images.githubusercontent.com/122446685/213442276-70c3f1b3-daf1-44e6-b986-c70ba2c8186a.png)
Same groupId and artifactId ?

**Comment by NewRunner2023** [comment]
yes

I mean if you look at the Build and Push action in the repo where the Java code lives 


![Screenshot 2023-01-19 at 12 27 48](https://user-images.githubusercontent.com/122446685/213443358-f02bcb2d-0b9d-4bd3-a4a5-5479ceb00062.png)

So you can see at line 1878, the built jar is going to:
https://maven.pkg.github.com/patricia-hartnett/gitHubActions_testQuarkus5/org/acme/my-github-action/999-SNAPSHOT/my-github-action-999-20230118.180945-1.jar

**Comment by NewRunner2023** [comment]
ok will add --verbose, one min

**Comment by NewRunner2023** [comment]
so line 14 in the actions.yml becomes 
      run: ~/.jbang/bin/jbang --repos 'github=https://maven.pkg.github.com/patricia-hartnett/gitHubActions_testQuarkus5/' --repos 'mavencentral' org.acme:my-github-action:999-SNAPSHOT --verbose


?

**Comment by gsmet** [comment]
add it just after `jbang`

**Comment by NewRunner2023** [comment]
thanks will do that now

**Comment by gsmet** [comment]
I personally suspect it will be a permission issue due to the repository being private. Not exactly sure how permissions work for Maven repositories of private projects.

**Comment by NewRunner2023** [comment]
I think it might be that alright
I can see:
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.acme:my-github-action:pom:999-SNAPSHOT from/to github (https://maven.pkg.github.com/patricia-hartnett/gitHubActions_testQuarkus5/): status code: 401, reason phrase: Unauthorized (401)

**Comment by NewRunner2023** [comment]
i can send you screengrabs of the full stack trace if you like ?

**Comment by gsmet** [comment]
Not really needed.

Can you try making the action repository public to see if that's what causes the issue?

**Comment by NewRunner2023** [comment]
Sorry was at lunch

Will try to use public repositories.

Will get back to you soon.
