### ISSUE TITLE
Codestarter for Kotlin

### ISSUE THREAD

**Issue by janpk** [quarkiverse/quarkus-github-action#121]
I have been playing with this for a couple of days now(version 1.x), and have created a working action with Kotlin. It's not that bad of a process, but it would be nice with a codestarter for Kotlin in addition to the Java one. To be able use Kotlin you basically have to generate a Java version of the action and copy a number of files and update versions in the pom.xml

I tried to create a codestarter locally, but there is something I do not understand about the dependencies included in the pom.xml file. The Quarkus platform in the generated pom.xml is 2.5.1.Final. That is quite a tad old, and I suspect that the platform version is why the Kotlin version ends up being also quite outdated, with version 1.5.31.

I would be happy to create a pull request with the Kotlin codestarter, but with the outdated Platform/Kotlin version, it makes little sense doing it., since you still would have to manually update the Kotlin version in the pom.xml, along with the platform version. Also the java version of the action generated also ends up with platform version 2.5.1.Final.

Do you have any insights into how to address this? What I use to generate the action is 

`mvn io.quarkus.platform:quarkus-maven-plugin:2.16.4.Final:create -DprojectGroupId=org.acme  -DprojectArtifactId=my-github-action4 -DprojectVersion=999-SNAPSHOT -DprojectName="My Action" -DprojectDescription="Description of my action" -Ddata="github-action-codestart.github-repository=my/action-github-repository" -Dextensions="kotlin,io.quarkiverse.githubaction:quarkus-github-action:1.0.1`

**Comment by gsmet** [comment]
Thanks for the feedback.

That is odd, I will have a look. You should have the latest Quarkus and Kotlin in there.

**Comment by aloubyansky** [comment]
@janpk could you please check the content of  the `~/.m2/repository/io/quarkus/registry/quarkus-platforms/1.0-SNAPSHOT/quarkus-platforms-1.0-SNAPSHOT.json`? Or wherever the local Maven repo path will be in your env?

**Comment by gsmet** [comment]
@janpk and please do it before trying to execute the command again as a new run might override what you have there.

**Comment by janpk** [comment]
So that is the reason. It is from Dec 9 , 2021. 

```json
{
  "platforms" : [ {
    "platform-key" : "io.quarkus.platform",
    "name" : "Quarkus Community Platform",
    "streams" : [ {
      "id" : "2.5",
      "releases" : [ {
        "version" : "2.5.1.Final",
        "member-boms" : [ "io.quarkus.platform:quarkus-bom::pom:2.5.1.Final", "io.quarkus.platform:quarkus-optaplanner-bom::pom:2.5.1.Final", "io.quarkus.platform:quarkus-kogito-bom::pom:2.5.1.Final", "io.quarkus.platform:quarkus-qpid-jms-bom::pom:2.5.1.Final", "io.quarkus.platform:quarkus-cassandra-bom::pom:2.5.1.Final", "io.quarkus.platform:quarkus-camel-bom::pom:2.5.1.Final", "io.quarkus.platform:quarkus-hazelcast-client::pom:2.5.1.Final", "io.quarkus.platform:quarkus-debezium-bom::pom:2.5.1.Final", "io.quarkus.platform:quarkus-blaze-persistence-bom::pom:2.5.1.Final", "io.quarkus.platform:quarkus-google-cloud-services-bom::pom:2.5.1.Final" ],
        "quarkus-core-version" : "2.5.1.Final"
      } ]
    }, {
      "id" : "2.6",
      "releases" : [ {
        "version" : "2.6.0.CR1",
        "member-boms" : [ "io.quarkus.platform:quarkus-bom::pom:2.6.0.CR1", "io.quarkus.platform:quarkus-optaplanner-bom::pom:2.6.0.CR1", "io.quarkus.platform:quarkus-kogito-bom::pom:2.6.0.CR1", "io.quarkus.platform:quarkus-qpid-jms-bom::pom:2.6.0.CR1", "io.quarkus.platform:quarkus-cassandra-bom::pom:2.6.0.CR1", "io.quarkus.platform:quarkus-amazon-services-bom::pom:2.6.0.CR1", "io.quarkus.platform:quarkus-camel-bom::pom:2.6.0.CR1", "io.quarkus.platform:quarkus-hazelcast-client::pom:2.6.0.CR1", "io.quarkus.platform:quarkus-debezium-bom::pom:2.6.0.CR1", "io.quarkus.platform:quarkus-blaze-persistence-bom::pom:2.6.0.CR1", "io.quarkus.platform:quarkus-google-cloud-services-bom::pom:2.6.0.CR1" ],
        "quarkus-core-version" : "2.6.0.CR1"
      } ]
    } ]
  } ]
}
```

Deleted it, and ran my Kotlin code starter and I got

```xml
    <kotlin.version>1.7.22</kotlin.version>
    <quarkus.platform.version>2.16.4.Final</quarkus.platform.version>
```
in the pom, and all else fell into place. 

Strange that **quarkus-platforms-1.0-SNAPSHOT.json** has not been updated in the .m2 repo for this long?

Thank you for the pointer!

**Comment by gsmet** [comment]
@aloubyansky so that confirms we have a real problem here as it happens from time to time and my recollection is that you don't even get a warning in this case (I didn't have one when I did my demo).

**Comment by janpk** [comment]
@gsmet Will create a PR tonight. Do I create it against only main or also against 1.x?

**Comment by aloubyansky** [comment]
@janpk is registry.quarkus.io/maven snapshot repo accissible in your environment? It does not have to be configured in your settings but a Maven client must be able to fetch artifacts from it.

**Comment by aloubyansky** [comment]
Meaning, could there be anything that blocks access to that repo?

**Comment by aloubyansky** [comment]
And to snapshot artifacts

**Comment by gsmet** [comment]
I just checked and it should be all good (we don't have any `javax` reference left).

I think you probably have an old version around. Make sure you rebuild the whole project with `mvn clean install`.

**Comment by gsmet** [comment]
Fixes! Thanks for the contribution. 

FYI, Quarkus 3.0 will come with Kotlin 1.8.
