### ISSUE TITLE
Codestart conflict

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-github-action#165]
The codestart conflict with a quarkus core one:
https://github.com/quarkiverse/quarkus-github-action/blob/main/runtime/src/main/codestarts/quarkus/github-action-codestart/codestart.yml#L2

and

https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/tooling/github-action/codestart.yml

**Comment by ia3andy** [comment]
the error: https://github.com/quarkusio/code.quarkus.io/actions/runs/5571937142/jobs/10177462429#step:6:83654

**Comment by ia3andy** [comment]
I think we should rename this codestart `quarkiverse-github-action`

**Comment by ia3andy** [comment]
I added a temporary fix on code.quarkus.io until this get fixed: https://github.com/quarkusio/code.quarkus.io/pull/1230

**Comment by gsmet** [comment]
I fixed it but I think we need to discuss it further.
