### ISSUE TITLE
Support injecting GHRepository into an action method

### ISSUE THREAD

**Issue by gsmet** [quarkiverse/quarkus-github-action#302]
An action is always executed in the context of a repository so we could inject the `GHRepository` in the action method.

Best way to track how it work is to look at `GitHubActionDotNames#INJECTABLE_TYPES` references.

We should probably have a method lazily returning a `GHRepository` in `GHEvent` - the repository name is in the `Context`.

We will need to add some doc here: https://github.com/quarkiverse/quarkus-github-action/blob/main/docs/modules/ROOT/pages/developer-reference.adoc?plain=1#L106

**Comment by gsmet** [comment]
@gcw-it in case you're interested seeing other facets of Quarkus. Feel free to push back, you looked interested in experimenting so trying to push stuff to you :).

**Comment by gcw-it** [comment]
@gsmet I‘ll have very little time on my hands in the coming week, but since the task doesn‘t seem to be time critical, I‘ll see, what I can figure out. 
Should any questions arise regarding this task, would it be appropriate to create a draft PR, or what would you recommend?

**Comment by gsmet** [comment]
Ask here or create a draft PR. 

And sure definitely not time critical and only take this if you’re interested and have time. No pressure.

**Comment by gcw-it** [comment]
No pressure perceived. I‘ll look into it as soon as time permits.
